
feign: 
  hystrix: 
    enabled: true       
  
server: 
  port: 10009
#  servlet:
#    context-path: /c1   
  
info: 
  app.name: mall
  company.name: nbs
  build.artifactId: $project.artifactId$
  build.version: $project.version$  

      
logging:
  level:
    org.springframework.cloud.openfeign: debug
